const schemeA = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 16,
    courses: [
      { type: "CC-1", credits: 4 },
      { type: "CC-M1", credits: 2 },
      { type: "MDC-1", credits: 3 },
      { type: "AEC-1", credits: 2 },
      { type: "SEC-1", credits: 3 },
      { type: "VAC-1", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title: " ",
    color: "#fff3cd",
  },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 16,
    courses: [
      { type: "CC-2", credits: 4 },
      { type: "CC-M2", credits: 2 },
      { type: "MDC-2", credits: 3 },
      { type: "AEC-2", credits: 2 },
      { type: "SEC-2", credits: 3 },
      { type: "VAC-2", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  {
    isDivider: true,
    title: " ",
    color: "#fff3cd",
  },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 16,
    courses: [
      { type: "CC-3", credits: 4 },
      { type: "CC-M3", credits: 4 },
      { type: "MDC-3", credits: 3 },
      { type: "AEC-3", credits: 2 },
      { type: "SEC-3", credits: 3 },
    ],
  },
  {
    isDivider: true,
    title: " ",
    color: "#fff3cd",
  },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 12,
    courses: [
      { type: "CC-4", credits: 4 },
      { type: "CC-M4(V)", credits: 4 },
      { type: "AEC-4", credits: 2 },
      { type: "VAC-3", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
  {
    isDivider: true,
    title: " ",
    color: "#fff3cd",
  },
  {
    number: 5,
    color: "#d9e2f3",
    totalCredits: 12,
    courses: [
      { type: "CC-5", credits: 4 },
      { type: "CC-M5(V)", credits: 4 },
      { type: "Intership", credits: 4 },
    ],
  },
  {
    isDivider: true,
    title: " ",
    color: "#fff3cd",
  },
  {
    number: 6,
    color: "#fbe5d6",
    totalCredits: 12,
    courses: [
      { type: "CC-6", credits: 4 },
      { type: "CC-M6", credits: 4 },
      { type: "CC-M7(V)", credits: 4 },
    ],
  },
  { isYearlyDivider: true, year: 3, color: "#d1ecf1" },
];

const schemeB = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "CC-A1", credits: 4 },
      { type: "CC-B1", credits: 4 },
      { type: "CC-C1", credits: 4 },
      { type: "CC-M1", credits: 2 },
      { type: "MDC-1", credits: 3 },
      { type: "AEC-1", credits: 2 },
      { type: "SEC-1", credits: 3 },
      { type: "VAC-1", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-A2", credits: 4 },
      { type: "CC-B2", credits: 4 },
      { type: "CC-C2", credits: 4 },
      { type: "CC-M2", credits: 2 },
      { type: "MDC-2", credits: 3 },
      { type: "AEC-2", credits: 2 },
      { type: "SEC-2", credits: 3 },
      { type: "VAC-2", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "MCC-A2", credits: 4 },
      { type: "MCC-A4", credits: 4 },
      { type: "MCC-A5", credits: 4 },
      { type: "CC-M3(V)", credits: 4 },
      { type: "MDC-3", credits: 3 },
      { type: "AEC-3", credits: 2 },
      { type: "SEC-3", credits: 3 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "MCC-A6", credits: 4 },
      { type: "MCC-A7", credits: 4 },
      { type: "MCC-A8", credits: 4 },
      { type: "DSE-A1", credits: 4 },
      { type: "CC-M4(V)", credits: 4 },
      { type: "AEC-4", credits: 2 },
      { type: "VAC-3", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 5,
    color: "#d9e2f3",
    totalCredits: 20,
    courses: [
      { type: "MCC-A9", credits: 4 },
      { type: "MCC-A10", credits: 4 },
      { type: "DSE-A2", credits: 4 },
      { type: "DSE-A3", credits: 4 },
      { type: "Internship", credits: 4 },
    ],
  },
  {
    isDivider: true,
    title: " ",
    color: "#fff3cd",
  },
  {
    number: 6,
    color: "#fbe5d6",
    totalCredits: 20,
    courses: [
      { type: "MCC-A11", credits: 4 },
      { type: "MCC-A12", credits: 4 },
      { type: "DSE-A4", credits: 4 },
      { type: "DSE-A5", credits: 4 },
      { type: "CC-M5(V)", credits: 4 },
    ],
  },
  { isYearlyDivider: true, year: 3, color: "#d1ecf1" },
  {
    isDivider: true,
    title: " ",
    color: "#fff3cd",
  },
  {
    number: 7,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "CC-H1", credits: 4 },
      { type: "CC-H2", credits: 4 },
      { type: "CC-H3", credits: 4 },
      { type: "DSE-H1", credits: 4 },
      { type: "PC-H1", credits: 4 },
      { type: "CC-HM1", credits: 4 },
    ],
  },
  // Semester 8 - Option A (Standard)
  {
    number: "8A",
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-H4", credits: 4 },
      { type: "CC-H5", credits: 4 },
      { type: "CC-H6", credits: 4 },
      { type: "DSE-H2", credits: 4 },
      { type: "PC-H2", credits: 4 },
      { type: "CC-HM2", credits: 4 },
    ],
  },
  // Divider
  {
    isDivider: true,
    title: "OR",
    color: "#fff3cd",
  },
  // Semester 8 - Option B (Project/Dissertation)
  {
    number: "8B",
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-H4", credits: 4 },
      { type: "CC-H5", credits: 4 },
      { type: "PROJECT/DISSERTATION", credits: 12 },
      { type: "CC-HM2", credits: 4 },
    ],
  },
  { isYearlyDivider: true, year: 4, color: "#d1ecf1" },
];

const schemeC = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 22,
    courses: [
      { type: "MCC-A1", credits: 4 },
      { type: "MCC-A2", credits: 4 },
      { type: "CC-M1", credits: 4 },
      { type: "MDC-1", credits: 3 },
      { type: "AEC-1", credits: 2 },
      { type: "SEC-1", credits: 3 },
      { type: "VAC-1", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 22,
    courses: [
      { type: "MCC-A3", credits: 4 },
      { type: "DSEC-A1", credits: 4 },
      { type: "CC-M2", credits: 4 },
      { type: "MDC-2", credits: 3 },
      { type: "AEC-2", credits: 2 },
      { type: "SEC-2", credits: 3 },
      { type: "VAC-2", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 22,
    courses: [
      { type: "MCC-A4", credits: 4 },
      { type: "MCC-A5", credits: 4 },
      { type: "CC-M3", credits: 4 },
      { type: "MDC-3", credits: 3 },
      { type: "AEC-3", credits: 2 },
      { type: "SEC-3", credits: 3 },
      { type: "VAC-3", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "MCC-A6", credits: 4 },
      { type: "MCC-A7", credits: 4 },
      { type: "MCC-A8", credits: 4 },
      { type: "DSE-A1", credits: 4 },
      { type: "CC-M4(V)", credits: 4 },
      { type: "AEC-4", credits: 2 },
      { type: "VAC-4", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 5,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "MCC-A9", credits: 4 },
      { type: "MCC-A10", credits: 4 },
      { type: "DSE-A2", credits: 4 },
      { type: "DSE-A3", credits: 4 },
      { type: "CC-M5(V)", credits: 4 },
      { type: "Internship", credits: 4 },
    ],
  },
  {
    isDivider: true,
    title:
      "4 credits of summer internship (earned post-semester 2 or 4) will be taken into account in the  5th semester for 3rd-year UG students who did not take an exit option.",
    color: "#fff3cd",
  },
  {
    number: 6,
    color: "#fbe5d6",
    totalCredits: 22,
    courses: [
      { type: "MCC-A11", credits: 4 },
      { type: "MCC-A12", credits: 4 },
      { type: "DSE-A4", credits: 4 },
      { type: "DSE-A5", credits: 4 },
      { type: "CC-M6(V)", credits: 4 },
      { type: "SEC-4", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 3, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 7,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "CC-H1", credits: 4 },
      { type: "CC-H2", credits: 4 },
      { type: "CC-H3", credits: 4 },
      { type: "DSE-H1", credits: 4 },
      { type: "PC-H1", credits: 4 },
      { type: "CC-HM1", credits: 4 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  // Semester 8 - Option A (Standard)
  {
    number: "8A",
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-H4", credits: 4 },
      { type: "CC-H5", credits: 4 },
      { type: "CC-H6", credits: 4 },
      { type: "DSE-H2", credits: 4 },
      { type: "PC-H2", credits: 4 },
      { type: "CC-HM2", credits: 4 },
    ],
  },
  // Divider
  {
    isDivider: true,
    title: "OR",
    color: "#fff3cd",
  },
  // Semester 8 - Option B (Project/Dissertation)
  {
    number: "8B",
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-H4", credits: 4 },
      { type: "CC-H5", credits: 4 },
      { type: "PROJECT/DISSERTATION", credits: 12 },
      { type: "CC-HM2", credits: 4 },
    ],
  },
  { isYearlyDivider: true, year: 4, color: "#d1ecf1" },
];

const schemeD = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "CC-A1", credits: 4 },
      { type: "CC-B1", credits: 4 },
      { type: "CC-C1", credits: 4 },
      { type: "CC-M1", credits: 2 },
      { type: "MDC-1", credits: 3 },
      { type: "AEC-1", credits: 2 },
      { type: "SEC-1", credits: 3 },
      { type: "VAC-1", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-A2", credits: 4 },
      { type: "CC-B2", credits: 4 },
      { type: "CC-C2", credits: 4 },
      { type: "CC-M2", credits: 2 },
      { type: "MDC-2", credits: 3 },
      { type: "AEC-2", credits: 2 },
      { type: "SEC-2", credits: 3 },
      { type: "VAC-2", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "CC-A3", credits: 4 },
      { type: "CC-B3", credits: 4 },
      { type: "CC-C3", credits: 4 },
      { type: "CC-M3", credits: 4 },
      { type: "MDC-3", credits: 3 },
      { type: "AEC-3", credits: 2 },
      { type: "SEC-3", credits: 3 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 20,
    courses: [
      { type: "CC-A4", credits: 4 },
      { type: "CC-B4", credits: 4 },
      { type: "CC-C4", credits: 4 },
      { type: "CC-M4(V)", credits: 4 },
      { type: "AEC-4", credits: 2 },
      { type: "VAC-3", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 5,
    color: "#d9e2f3",
    totalCredits: 20,
    courses: [
      { type: "CC-A5", credits: 4 },
      { type: "CC-B5", credits: 4 },
      { type: "CC-C5", credits: 4 },
      { type: "CC-M5(V)", credits: 4 },
      { type: "Internship", credits: 4 },
    ],
  },
  {
    isDivider: true,
    title:
      "4 credits of summer internship (earned post-semester 2 or 4) will be taken into account in the  5th semester for 3rd-year UG students who did not take an exit option.",
    color: "#fff3cd",
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 6,
    color: "#fbe5d6",
    totalCredits: 20,
    courses: [
      { type: "CC-A6", credits: 4 },
      { type: "CC-B6", credits: 4 },
      { type: "CC-C6", credits: 4 },
      { type: "CC-M6(V)", credits: 4 },
      { type: "CC-M7(V)", credits: 4 },
    ],
  },
  { isYearlyDivider: true, year: 3, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 7,
    color: "#d9e2f3",
    totalCredits: 24,
    courses: [
      { type: "CC-H1", credits: 4 },
      { type: "CC-H2", credits: 4 },
      { type: "CC-H3", credits: 4 },
      { type: "DSE-H1", credits: 4 },
      { type: "PC-H1", credits: 4 },
      { type: "CC-HM1", credits: 4 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  // Semester 8 - Option A (Standard)
  {
    number: "8A",
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-H4", credits: 4 },
      { type: "CC-H5", credits: 4 },
      { type: "CC-H6", credits: 4 },
      { type: "DSE-H2", credits: 4 },
      { type: "PC-H2", credits: 4 },
      { type: "CC-HM2", credits: 4 },
    ],
  },
  {
    isDivider: true,
    title: "OR",
    color: "#fff3cd",
  },
  // Semester 8 - Option B (Project/Dissertation)
  {
    number: "8B",
    color: "#fbe5d6",
    totalCredits: 24,
    courses: [
      { type: "CC-H4", credits: 4 },
      { type: "CC-H5", credits: 4 },
      { type: "PROJECT/DISSERTATION", credits: 12 },
      { type: "CC-HM2", credits: 4 },
    ],
  },
  { isYearlyDivider: true, year: 4, color: "#d1ecf1" },
];

const schemeP = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-1", credits: 4 },
      { type: "CC-2", credits: 4 },
      { type: "CC-3", credits: 4 },
      { type: "CC-4", credits: 4 },
      { type: "PC-1", credits: 4 },
      { type: "PC-2", credits: 4 },
      { type: "SEMINAR", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-5", credits: 4 },
      { type: "CC-6", credits: 4 },
      { type: "CC-7", credits: 4 },
      { type: "CC-8", credits: 4 },
      { type: "PC-3", credits: 4 },
      { type: "PC-4", credits: 4 },
      { type: "CHM", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-9", credits: 4 },
      { type: "CC-10", credits: 4 },
      { type: "DEC-1", credits: 4 },
      { type: "DEC-2", credits: 4 },
      { type: "PC-5", credits: 4 },
      { type: "PC-6", credits: 4 },
      { type: "OEC", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-11", credits: 4 },
      { type: "CC-12", credits: 4 },
      { type: "DEC-3", credits: 4 },
      { type: "DEC-4", credits: 4 },
      { type: "PC-7", credits: 4 },
      { type: "PC-8", credits: 4 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title:
      "SCHEME OF SEMESTER-4 WHEN A STUDENT OPTS FOR DISSERTATION OR PROJECT WORK",
    color: "#fff3cd",
  },
  { isDivider: true, title: "OR", color: "#fff3cd" },
  {
    number: "4A",
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "DEC-3", credits: 4 },
      { type: "DEC-4", credits: 4 },
      { type: "DEC-5", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title: "OR",
    color: "#fff3cd",
  },
  {
    number: "4B",
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-11", credits: 4 },
      { type: "DEC-3", credits: 4 },
      { type: "DEC-4", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
];

const schemeQ = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-1", credits: 4 },
      { type: "CC-2", credits: 4 },
      { type: "CC-3", credits: 4 },
      { type: "CC-4", credits: 4 },
      { type: "CC-5", credits: 4 },
      { type: "PC-1", credits: 4 },
      { type: "SEMINAR", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-6", credits: 4 },
      { type: "CC-7", credits: 4 },
      { type: "CC-8", credits: 4 },
      { type: "CC-9", credits: 4 },
      { type: "CC-10", credits: 4 },
      { type: "PC-2", credits: 4 },
      { type: "CHM", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-11", credits: 4 },
      { type: "CC-12", credits: 4 },
      { type: "DEC-1", credits: 4 },
      { type: "DEC-2", credits: 4 },
      { type: "DEC-3", credits: 4 },
      { type: "PC-3", credits: 4 },
      { type: "OEC", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-13", credits: 4 },
      { type: "CC-14", credits: 4 },
      { type: "DEC-4", credits: 4 },
      { type: "DEC-5", credits: 4 },
      { type: "DEC-6", credits: 4 },
      { type: "PC-4", credits: 4 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title:
      "SCHEME OF SEMESTER-4 WHEN A STUDENT OPTS FOR DISSERTATION OR PROJECT WORK",
    color: "#fff3cd",
  },
  { isDivider: true, title: "OR", color: "#fff3cd" },
  {
    number: "4A",
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "DEC-4", credits: 4 },
      { type: "DEC-5", credits: 4 },
      { type: "DEC-6", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title: "OR",
    color: "#fff3cd",
  },
  {
    number: "4B",
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-13", credits: 4 },
      { type: "DEC-5", credits: 4 },
      { type: "DEC-6", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
];

const schemeR = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-1", credits: 4 },
      { type: "CC-2", credits: 4 },
      { type: "CC-3", credits: 4 },
      { type: "CC-4", credits: 4 },
      { type: "DEC-1", credits: 4 },
      { type: "DEC-2", credits: 4 },
      { type: "SEMINAR", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-5", credits: 4 },
      { type: "CC-6", credits: 4 },
      { type: "CC-7", credits: 4 },
      { type: "CC-8", credits: 4 },
      { type: "DEC-3", credits: 4 },
      { type: "DEC-4", credits: 4 },
      { type: "CHM", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-9", credits: 4 },
      { type: "CC-10", credits: 4 },
      { type: "DEC-5", credits: 4 },
      { type: "DEC-6", credits: 4 },
      { type: "DEC-7", credits: 4 },
      { type: "DEC-8", credits: 4 },
      { type: "OEC", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-11", credits: 4 },
      { type: "CC-12", credits: 4 },
      { type: "DEC-9", credits: 4 },
      { type: "DEC-10", credits: 4 },
      { type: "DEC-11", credits: 4 },
      { type: "DEC-12", credits: 4 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title:
      "SCHEME OF SEMESTER-4 WHEN A STUDENT OPTS FOR DISSERTATION OR PROJECT WORK",
    color: "#fff3cd",
  },
  { isDivider: true, title: "OR", color: "#fff3cd" },
  {
    number: "4A",
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "DEC-9", credits: 4 },
      { type: "DEC-10", credits: 4 },
      { type: "DEC-11", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title: "OR",
    color: "#fff3cd",
  },
  {
    number: "4B",
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-11", credits: 4 },
      { type: "DEC-9", credits: 4 },
      { type: "DEC-10", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
];

const schemeS = [
  {
    number: 1,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-1", credits: 4 },
      { type: "CC-2", credits: 4 },
      { type: "CC-3", credits: 4 },
      { type: "CC-4", credits: 4 },
      { type: "CC-5", credits: 4 },
      { type: "DEC-1", credits: 4 },
      { type: "SEMINAR", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 2,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-6", credits: 4 },
      { type: "CC-7", credits: 4 },
      { type: "CC-8", credits: 4 },
      { type: "CC-9", credits: 4 },
      { type: "CC-10", credits: 4 },
      { type: "DEC-2", credits: 4 },
      { type: "CHM", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 1, color: "#d1ecf1" },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 3,
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "CC-11", credits: 4 },
      { type: "CC-12", credits: 4 },
      { type: "DEC-3", credits: 4 },
      { type: "DEC-4", credits: 4 },
      { type: "DEC-5", credits: 4 },
      { type: "DEC-6", credits: 4 },
      { type: "OEC", credits: 2 },
    ],
  },
  { isDivider: true, title: " ", color: "#fff3cd" },
  {
    number: 4,
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-13", credits: 4 },
      { type: "CC-14", credits: 4 },
      { type: "DEC-7", credits: 4 },
      { type: "DEC-8", credits: 4 },
      { type: "DEC-9", credits: 4 },
      { type: "DEC-10", credits: 4 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title:
      "SCHEME OF SEMESTER-4 WHEN A STUDENT OPTS FOR DISSERTATION OR PROJECT WORK",
    color: "#fff3cd",
  },
  { isDivider: true, title: "OR", color: "#fff3cd" },
  {
    number: "4A",
    color: "#d9e2f3",
    totalCredits: 26,
    courses: [
      { type: "DEC-7", credits: 4 },
      { type: "DEC-8", credits: 4 },
      { type: "DEC-9", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  {
    isDivider: true,
    title: "OR",
    color: "#fff3cd",
  },
  {
    number: "4B",
    color: "#fbe5d6",
    totalCredits: 26,
    courses: [
      { type: "CC-13", credits: 4 },
      { type: "DEC-7", credits: 4 },
      { type: "DEC-8", credits: 4 },
      { type: "PROJECT WORK/DISSERTATION", credits: 12 },
      { type: "EEC", credits: 2 },
    ],
  },
  { isYearlyDivider: true, year: 2, color: "#d1ecf1" },
];

const curriculumSchemes = {
  "Scheme A": schemeA,
  "Scheme B": schemeB,
  "Scheme C": schemeC,
  "Scheme D": schemeD,
  "Scheme P": schemeP,
  "Scheme Q": schemeQ,
  "Scheme R": schemeR,
  "Scheme S": schemeS,
};

module.exports = curriculumSchemes;
