const dummyCourseData = {
  programmeName: "B.Tech Computer Science",
  semester: "3rd Semester",
  natureOfCourse: "Theory + Practical",
  courseName: "Data Structures",
  courseCode: "PCC-CSE-201",
  courseType: "Core",
  credits: { theory: 3, practical: 1, total: 4 },
  marks: {
    internalTheory: 20,
    internalPractical: 10,
    internalTotal: 30,
    endTermTheory: 50,
    endTermPractical: 20,
    endTermTotal: 70,
    maxMarks: 100,
  },
  examDuration: "2 hours",
  examInfo: { totalQuestions: 9 },
  units: [
    { id: "Unit I", topics: "Introduction to Arrays, Linked Lists", hours: 15 },
    { id: "Unit II", topics: "Stacks, Queues, Trees", hours: 15 },
  ],
  totalHours: 30,
  resources: ["Book A by Author X", "Book B by Author Y"],
  clos: ["CLO1", "CLO2", "CLO3", "CLO4"],
  nepMapping: {
    employability: "Content for Employability",
    skillEnhancement: "Content for Skill Enhancement",
    communicationDevelopment: "Content for Communication Development",
    indianKnowledgeSystem: "Content for IKS",
    environmentalAwareness: "Content for Environment",
    currentIssues: "Content for Current Issues",
    womenEmpowerment: "Content for Women Empowerment",
    publicPolicies: "Content for Public Policies",
    anyOther: "Any other content",
  },
};

module.exports = { dummyCourseData };
